// Default scenarios per market. Canadian tax defaults assume a top-bracket
// British Columbia resident (2026). Vietnamese defaults follow the individual
// landlord regime (Circular 40/2021) and current securities tax rules.

export const DEFAULTS = {
  CA: {
    market: 'CA',
    price: 530000,
    downPct: 25,
    closingPct: 2,
    rate: 4.5,
    amort: 30,
    rent: 2400,
    vacancy: 2,
    propTax: 2000,
    insurance: 1200,
    strata: 466,
    other: 100,
    appreciation: 3,
    rentGrowth: 2,
    expInflation: 2.5,
    sellingPct: 4,
    horizon: 25,
    claimCCA: false,
    buildingPct: 70,
    ccaRate: 4,
    tax: {
      marginal: 53.5,
      dividend: 36.54,
      cgInclusion: 50,
      retirement: 30,
      lossOffset: true,
      vnRentalRate: 10,
      vnRentalThreshold: 100e6,
      vnSaleRate: 2,
      vnDividend: 5,
      vnSale: 0.1,
    },
    stocks: {
      stockReturn: 7,
      dividendYield: 2,
      fee: 0.2,
      depositRate: 3,
      tfsaRoom: 102000,
      rrspRoom: 60000,
    },
    // Bear / bull cases are shifts (in percentage points) applied on top of
    // each house's own inputs and the shared stock assumptions.
    scenarios: {
      bear: { appreciation: -2, rentGrowth: -1, vacancy: 3, rate: 1.5, stockReturn: -2 },
      bull: { appreciation: 1.5, rentGrowth: 1, vacancy: -1, rate: -1, stockReturn: 2 },
    },
    damming: {
      homeValue: 1200000,
      homeGrowth: 3,
      homeBalance: 600000,
      homeRate: 4.2,
      homeAmort: 25,
      helocRate: 4.95,
      helocLTV: 65,
      totalLTV: 80,
      capitalize: true,
    },
  },
  VN: {
    market: 'VN',
    price: 4e9,
    downPct: 30,
    closingPct: 0.5,
    rate: 9,
    amort: 25,
    rent: 15e6,
    vacancy: 5,
    propTax: 0,
    insurance: 0,
    strata: 1.5e6,
    other: 0,
    appreciation: 5,
    rentGrowth: 3,
    expInflation: 3,
    sellingPct: 1,
    horizon: 20,
    claimCCA: false,
    buildingPct: 0,
    ccaRate: 0,
    tax: {
      marginal: 0,
      dividend: 0,
      cgInclusion: 0,
      retirement: 0,
      lossOffset: false,
      vnRentalRate: 10,
      vnRentalThreshold: 100e6,
      vnSaleRate: 2,
      vnDividend: 5,
      vnSale: 0.1,
    },
    stocks: {
      stockReturn: 11,
      dividendYield: 2,
      fee: 0.5,
      depositRate: 5,
      tfsaRoom: 0,
      rrspRoom: 0,
    },
    scenarios: {
      bear: { appreciation: -4, rentGrowth: -2, vacancy: 5, rate: 3, stockReturn: -4 },
      bull: { appreciation: 3, rentGrowth: 1.5, vacancy: -2, rate: -1.5, stockReturn: 3 },
    },
    damming: null,
  },
};
